IF OBJECT_ID('[dbo].[f1]') IS NOT NULL
	DROP PROCEDURE [dbo].[f1];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
CREATE PROCEDURE [dbo].[f1]
AS
    SELECT 1
GO
