IF OBJECT_ID('[dbo].[f2]') IS NOT NULL
	DROP PROCEDURE [dbo].[f2];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
CREATE PROCEDURE [dbo].[f2]
AS
    SELECT 2
GO
