IF OBJECT_ID('[dbo].[f3]') IS NOT NULL
	DROP PROCEDURE [dbo].[f3];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
CREATE PROCEDURE [dbo].[f3]
AS
    SELECT 3
GO
