IF OBJECT_ID('[dbo].[f4]') IS NOT NULL
	DROP PROCEDURE [dbo].[f4];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
CREATE PROCEDURE [dbo].[f4]
AS
    SELECT 4
GO
